import DashboardPanel from "../components/dashboard-panel/page";
import { Ubuntu, Inter } from "next/font/google";
import "@/app/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={`dashboard-layout inter.className`}>
      <aside className="dashboard-sidepanel">
        <DashboardPanel />
      </aside>
      <section className="dashboard-content">{children}</section>
    </div>
  );
}
